---
topics: ["DeFi","DEX","Liquidity Provider","decentralized finance","smart contract","smartcontract"]
base_directory: "/Users/hamidmoradi/Documents/Papers/aggregate all DeFi paper/papers"
filter_words:
  [
    # "protocols",
    # "protocol",
    # "decentralized",
    # "lending",
    # "collateralized",
    # "cryptoasset",
    # "investors",
    # "Aave",
    # "application",
    # "finance",
    "defi ",
    "DeFi ",
    "decentralized finance",
    # "ecosystem",
    # "supply",
    # "financial",
    # "stablecoin",
    # "asset",
    # "risk",
    # "traditional",
    # "banking",
    # "Zero-knowledge",
    # "Zero-knowledge proof",
    # "blockchain",
     "Defis ",
    # "centralized",
    # "privacy",
    # "UNISWAP",
    # "mpermanent Loss",
    # "Liquidity Provider",
    # "DEX",
    #"Ethereum",
    # "mainnet",
    # "order book",
    # "exchanges",
    # "swap",
    # "currencies",
    # "token",
    # "tokens",
    # "investors",
    # "pools",
    # "trading",
    # "loans",
    # "insurance",
    #  "USD",
    # "developers",
    # "attacks",
    # "security",
    # "exploits",
    # "exploit",
    # "USDT",
    # "liquidation",
    # "vulnerable",
    # "cash flow",
    # "transactions",
    # "transaction",
    #"Smart Contracts",
    #"Smart Contract",
    #"smart contracts",
    #"smartcontracts",
    #"smartcontract",
    # "sandwich",
    # "Economics",
    # "Flash Loan",
    # "Stake",
    # "Borrow",
    # "Oracles",
    #"oracle",
    # "Cryptocurrencies",
    # "Currency",
     # "Money",
    # "Bitcoin",
    
  ] 
